name: C CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install libs and requirements
      run: sudo apt-get install libgraphviz-dev valgrind
    - name: make
      run: make
    - name: make tests
      run: make tests
