name: CMake CI

on:
  push:
    branches: [ beta ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install libs
      run: sudo apt-get install libgraphviz-dev libomp-dev
    - name: configure cmake
      run: mkdir build/ && cd build/ && cmake ..
    - name: build
      run: cd build/ && cmake --build .
    - name: CTest
      run: cd build/ && ctest
